let arr = [
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
    {
        product: 'Shirt',
        sale_p: `${320800}$`,
        cost_p: 61,
        stock: 45,
        date: new Date().toLocaleDateString(),
    },
]

export default arr;